### ISSUE TITLE
Change License, JDownloader is actually Open Source

### ISSUE THREAD

**Issue by EuriNaiz** [flathub/org.jdownloader.JDownloader#30] opened 2023-06-26 05:43 UTC
Right now, GNOME software marks JDownloader as insecure because it is closed source, but it isn't true, JDownloader is open source and its code can be found in their [official website](https://support.jdownloader.org/Knowledgebase/Article/View/setup-ide-eclipse) and in a [mirror](https://github.com/mirror/jdownloader), even, when the app is installed, the GPLv3 can be found in ~/.var/app/org.jdownloader.JDownloader/data/jdownloader/license.txt

Please, fix it.

**Comment by KuSh** [comment] 2023-06-27 22:17
Duplicate of #1 

You're welcome to push a PR to build the flatpak from sources. I wasn't able to make it functional after a rapid first try

**Closed by KuSh** 2023-06-27 22:17 UTC

**Comment by teohhanhui** [comment] 2024-08-18 09:32
Just because it's not easy to build from source in a flathubbot / flatpak-builder environment, doesn't mean the software is *not* open source. 

Of course, that also doesn't tell you that the software *is* open source. That'd have to be verified through other means.
